spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cache:
    type: redis
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
